"""
Audio Merger Utility
--------------------
Merges all MP3 files generated by Inworld TTS into a single audiobook file.

Requirements:
- pydub (`pip install pydub`)
- ffmpeg (must be installed and in PATH)
"""

import os
from pydub import AudioSegment


def merge_audio_files(input_dir: str, output_filename: str):
    """
    Merge all MP3 audio chunks (output_part_001.mp3, etc.) into one file.
    """
    # Get only chunk files that match the pattern
    audio_files = sorted(
        [
            f for f in os.listdir(input_dir)
            if f.startswith("output_part_") and f.endswith(".mp3")
        ]
    )

    if not audio_files:
        print("⚠️ No audio chunks found to merge.")
        return

    print(f"🎶 Found {len(audio_files)} audio chunks. Merging...")

    # Load the first file
    combined = AudioSegment.from_mp3(os.path.join(input_dir, audio_files[0]))

    # Append the rest
    for filename in audio_files[1:]:
        filepath = os.path.join(input_dir, filename)
        segment = AudioSegment.from_mp3(filepath)
        combined += segment
        print(f"   ➕ Added: {filename}")

    # Export the merged file
    combined.export(output_filename, format="mp3")
    print(f"\n✅ Merged audiobook saved as: {output_filename}")


if __name__ == "__main__":
    merge_audio_files(
        input_dir="output",
        output_filename="output/merged_audiobook.mp3"
    )